const MAIN_PREFIX = "MAIN";
const LAYOUT_PREFIX = "LAYOUT";

export const SET_URL = `${MAIN_PREFIX}/SET_URL`;
export const SET_URL_IS_LOADED = `${MAIN_PREFIX}/SET_URL_IS_LOADED`;
export const SET_REPO = `${MAIN_PREFIX}/SET_REPO`;
export const SET_ISSUES = `${LAYOUT_PREFIX}/SET_ISSUES`;
